# Generated by Django 5.0.4 on 2024-04-07 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_messages_alter_category_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Contact',
        ),
    ]
